#!/bin/bash
function get_brightness {
 brightnessctl | grep % | sort| cut -c 28-30
}



function send_notification() {
    brightness=$(get_brightness)
	dunstify -a "changebrightness" -u low -r "9991" -h int:value:"$brightness" -i "brightness-$1" "Brightness: ${brightness}" -t 2000
}

case $1 in
up)
	brightnessctl set +1%
	send_notification $1
	;;
down)
	brightnessctl set 1%-
	send_notification $1
	;;
esac
